import { prisma } from "../lib/prisma";






const TEST_EMAIL = "hdddwhewiuydiywe"; // <-- apna login email daal

const categories = [
    "🍔 Food",
    "🏠 Home",
    "🏥 Health",
    "🛍️ Shopping",
    "📦 Miscellaneous",
    "✨ Other",
];

const titles: Record<string, string[]> = {
    "🍔 Food": ["Pizza", "Burger", "Cafe", "Lunch", "Dinner", "Dominos"],
    "🏠 Home": ["Electricity Bill", "Water Bill", "Furniture", "Gas Refill"],
    "🏥 Health": ["Medicine", "Doctor Visit", "Gym", "Protein"],
    "🛍️ Shopping": ["Amazon", "Shoes", "Clothes", "Headphones"],
    "📦 Miscellaneous": ["Recharge", "Subscription", "Stationery", "Gift"],
    "✨ Other": ["Movie", "Coffee", "Trip", "Random Expense"],
};

function randomCategory() {
    return categories[Math.floor(Math.random() * categories.length)];
}

function randomAmount() {
    return Number((Math.random() * 4500 + 200).toFixed(2));
}

function randomDate() {
    const currentYear = new Date().getFullYear();

    const start = new Date(currentYear, 0, 1).getTime();
    const end = Date.now();

    return new Date(start + Math.random() * (end - start));
}

async function seed() {
    const user = await prisma.user.findUnique({
        where: {
            email: TEST_EMAIL,
        },
    });

    if (!user) {
        console.log("❌ User not found");
        return;
    }

    for (let i = 0; i < 200; i++) {
        const category = randomCategory();
        const titleList = titles[category];

        await prisma.expense.create({
            data: {
                title: titleList[Math.floor(Math.random() * titleList.length)],
                category,
                amount: randomAmount(),
                description: "Generated by Seed Script",
                date: randomDate(),
                spenderId: user.id,
            },
        });
    }

    console.log("✅ 200 expenses inserted successfully.");
}

seed()
    .catch(console.error)
    .finally(async () => {
        await prisma.$disconnect();
    });